Add missing == operator in geo_polygon
fixes:
vision/kwiver-v2/kwiver-v2/vital/types/metadata.cxx:36:16:
  error: no match for ‘operator==’ (operand types are ‘const kwiver::vital::geo_polygon’ and ‘const kwiver
::vital::geo_polygon’)
   36 |     return lhs == rhs;